### ISSUE TITLE
Definition of CI function in B-MLE

### ISSUE THREAD

**Issue by taniokay** [contactmodel/COVID19-Japan-Reff#8]
In calculation of 95% CI, the function `CI` is like:

> `CI <- function(par_CI){return(2*(-llk(par_CI)+llk(opt_est$value)))}`

But `opt_est$value` is the value of `llk` corresponding to the optimal Rt (`opt_est$par`), so I suppose the function should be like :

> `CI <- function(par_CI){return(2*(-llk(par_CI)+ opt_est$value))}`

**Comment by aakhmetz** [comment]
Thank you for noticing - it was corrected

**Comment by taniokay** [comment]
thanks for your replying and correcting!
